#!/usr/bin/env bash
# smokemon installer (Linux node or hub). Installs deps, grants fping/mtr CAP_NET_RAW
# (no sudo), writes /etc/smokemon.env, installs + enables systemd units. Works two ways:
#
#   local:   sudo ./install.sh --node NAME [--hub-url http://HUB-HOST:8765/ingest --secret S]
#   one-line: curl -fsSL https://raw.githubusercontent.com/oovets/smokemon/main/install.sh \
#               | sudo bash -s -- --node NAME [--hub-url URL --secret S]
#   hub:     ... --hub --secret S          (--secret must match between node and hub)
#
# When piped (no local checkout) it clones the repo to $SMOKEMON_DIR (default /opt/smokemon).
set -euo pipefail

MODE="node"; NODE_NAME="$(hostname)"; HUB_URL=""   # empty -> local-only node (ship no-ops)
SECRET=""; TARGETS="1.1.1.1,192.168.0.1"
while [ $# -gt 0 ]; do
    case "$1" in
        --hub) MODE="hub"; shift ;;
        --node) NODE_NAME="$2"; shift 2 ;;
        --hub-url) HUB_URL="$2"; shift 2 ;;
        --secret) SECRET="$2"; shift 2 ;;
        --targets) TARGETS="$2"; shift 2 ;;
        *) echo "unknown argument: $1" >&2; exit 1 ;;
    esac
done
[ "$(id -u)" -eq 0 ] || { echo "run as root (sudo)." >&2; exit 1; }

# Use the local checkout if run from one, otherwise clone (curl-piped).
SELF="${BASH_SOURCE[0]:-}"
if [ -n "$SELF" ] && [ -f "$(dirname "$SELF")/deploy/systemd/smokemon-hub.service" ]; then
    DIR="$(cd "$(dirname "$SELF")" && pwd)"
else
    DIR="${SMOKEMON_DIR:-/opt/smokemon}"
    REPO="${SMOKEMON_REPO:-https://github.com/oovets/smokemon.git}"
    command -v git >/dev/null 2>&1 || { apt-get update -qq && apt-get install -y --no-install-recommends git; }
    if [ -d "$DIR/.git" ]; then echo "==> updating $DIR"; git -C "$DIR" pull -q --ff-only
    else echo "==> cloning $REPO -> $DIR"; git clone -q --depth 1 "$REPO" "$DIR"; fi
fi

USER_NAME="${SUDO_USER:-$(whoami)}"
PYTHON="$(command -v python3)"
ENV_FILE="/etc/smokemon.env"
UNIT_DIR="/etc/systemd/system"
echo "==> smokemon install: mode=$MODE dir=$DIR user=$USER_NAME python=$PYTHON"

echo "==> apt deps"
apt-get update -qq
if [ "$MODE" = "hub" ]; then
    # hub runs iperf3 -s by default (see units below) so nodes have a bandwidth target.
    apt-get install -y --no-install-recommends iperf3 python3-pip python3-matplotlib python3-numpy
else
    apt-get install -y --no-install-recommends fping iperf3 iw mtr-tiny python3-pip
    echo "==> CAP_NET_RAW on fping/mtr (skip sudo)"
    for bin in "$(command -v fping || true)" "$(command -v mtr-packet || true)"; do
        [ -n "$bin" ] && setcap cap_net_raw+ep "$bin" && echo "    setcap $bin" || true
    done
fi
echo "==> plotext (local TUI)"
sudo -u "$USER_NAME" "$PYTHON" -m pip install --user plotext 2>/dev/null \
    || sudo -u "$USER_NAME" "$PYTHON" -m pip install --user --break-system-packages plotext 2>/dev/null \
    || echo "    (plotext skipped — install manually for local TUI)"

# nodes bandwidth-test to the hub by default: derive the iperf target (host only, no
# scheme/port/path) from --hub-url unless SMOKEMON_IPERF_SERVER is already set.
IPERF_SERVER="${SMOKEMON_IPERF_SERVER:-}"
if [ -z "$IPERF_SERVER" ] && [ -n "$HUB_URL" ]; then
    h="${HUB_URL#*://}"; h="${h%%/*}"; IPERF_SERVER="${h%%:*}"
fi

echo "==> writing $ENV_FILE"
{
    echo "# smokemon config (generated by install.sh)"
    echo "PYTHONPATH=$DIR"
    echo "SMOKEMON_DB=$DIR/data/smokemon.db"
    echo "SMOKEMON_NODE=$NODE_NAME"
    if [ "$MODE" = "hub" ]; then
        echo "SMOKEMON_HUB_DB=$DIR/data/smokemon-hub.db"
        echo "SMOKEMON_HUB_BIND=0.0.0.0"
        echo "SMOKEMON_HUB_PORT=8765"
    else
        echo "SMOKEMON_TARGETS=$TARGETS"
        echo "SMOKEMON_MTR_SUDO=0"
        [ -n "$HUB_URL" ] && echo "SMOKEMON_HUB_URL=$HUB_URL"
        [ -n "$IPERF_SERVER" ] && echo "SMOKEMON_IPERF_SERVER=$IPERF_SERVER"
    fi
    echo "SMOKEMON_HUB_SECRET=$SECRET"
} > "$ENV_FILE"
chmod 600 "$ENV_FILE"
mkdir -p "$DIR/data"; chown -R "$USER_NAME" "$DIR/data"

echo "==> smoke command (/usr/local/bin/smoke)"
# A real executable on PATH works in every shell immediately - no relogin, no profile
# sourcing (/etc/profile.d only loads in login shells, and not at all under zsh/fish).
# Bake the resolved paths in so `smoke`/`smoke fleet` find the right DB without reading
# the root-owned /etc/smokemon.env (the secret stays out of this world-readable file).
rm -f /etc/profile.d/smokemon.sh   # retire the old login-shell-only helper
BIN=/usr/local/bin
cat > "$BIN/smoke" <<EOF
#!/bin/sh
# smokemon viewer (generated by install.sh)
export PYTHONPATH="$DIR"
export SMOKEMON_DB="$DIR/data/smokemon.db"
export SMOKEMON_HUB_DB="$DIR/data/smokemon-hub.db"
export SMOKEMON_NODE="$NODE_NAME"
exec "$PYTHON" -m smokemon.cli "\$@"
EOF
chmod 755 "$BIN/smoke"
for sub in live kiosk png; do
    cat > "$BIN/smoke$sub" <<EOF
#!/bin/sh
exec "$BIN/smoke" $sub "\$@"
EOF
    chmod 755 "$BIN/smoke$sub"
done

install_unit() {
    sed -e "s|__USER__|$USER_NAME|g" -e "s|__SMOKEMON_DIR__|$DIR|g" \
        -e "s|__PYTHON__|$PYTHON|g" -e "s|__ENV_FILE__|$ENV_FILE|g" \
        "$DIR/deploy/systemd/$1" > "$UNIT_DIR/$1"
    echo "    installed $1"
}

echo "==> systemd units"
if [ "$MODE" = "hub" ]; then
    install_unit smokemon-hub.service
    install_unit smokemon-iperf-server.service
    systemctl daemon-reload
    systemctl enable --now smokemon-hub.service smokemon-iperf-server.service
    echo "==> done. Hub on :8765 + iperf3 -s on :5201 — systemctl status smokemon-hub"
    echo "    try now:  smoke fleet --hub-url http://localhost:8765   (or open http://localhost:8765/)"
else
    for u in smokemon-collect-fast.service smokemon-collect-slow.service \
             smokemon-iperf.service smokemon-iperf.timer \
             smokemon-shipper.service smokemon-shipper.timer; do install_unit "$u"; done
    systemctl daemon-reload
    systemctl enable --now smokemon-collect-fast.service smokemon-collect-slow.service \
        smokemon-iperf.timer smokemon-shipper.timer
    echo "==> done. journalctl -u smokemon-collect-fast -f"
    echo "    try now:  smoke   (give the collectors a minute to gather data first)"
fi
