#!/usr/bin/env bash
# smokemon installer. One command, either role:
#
#   hub:   curl -fsSL https://raw.githubusercontent.com/oovets/smokemon/main/install.sh | sudo bash -s -- --hub
#   node:  curl -fsSL .../install.sh | sudo bash -s -- --hub-url http://HUB:8765/ingest --secret S
#
# The hub install prints the exact node command, secret filled in, and installs `smokemon-fleet`
# so the rest of the fleet is one more command.
#
# There is no checkout on the target. smokemon is stdlib-only, so it ships as a single zipapp
# built here and dropped at /usr/local/lib/smokemon.pyz. Nothing to pull, nothing to go stale,
# and no git history for a future rewrite to break: reinstalling is just overwriting one file.
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive   # a debconf prompt would hang a piped `curl | bash`

MODE="node"
NODE_NAME="$(hostname)"
HUB_URL=""
SECRET=""
TARGETS="1.1.1.1,gw"
BRANCH="${SMOKEMON_BRANCH:-main}"
REPO="${SMOKEMON_REPO:-oovets/smokemon}"

while [ $# -gt 0 ]; do
    case "$1" in
        --hub)      MODE="hub"; shift ;;
        --node)     NODE_NAME="$2"; shift 2 ;;
        --hub-url)  HUB_URL="$2"; shift 2 ;;
        --secret)   SECRET="$2"; shift 2 ;;
        --targets)  TARGETS="$2"; shift 2 ;;
        --branch)   BRANCH="$2"; shift 2 ;;
        *) echo "unknown argument: $1" >&2; exit 1 ;;
    esac
done
[ "$(id -u)" -eq 0 ] || { echo "run as root (sudo)." >&2; exit 1; }

AGENT=/usr/local/lib/smokemon.pyz
DATA_DIR=/var/lib/smokemon
ENV_FILE=/etc/smokemon.env
UNIT_DIR=/etc/systemd/system
SVC_USER="${SMOKEMON_USER:-smokemon}"

# A hub with no secret accepts unauthenticated ingest from anyone, and it binds 0.0.0.0.
if [ "$MODE" = "hub" ] && [ -z "$SECRET" ]; then
    SECRET="$(head -c 32 /dev/urandom | base64 | tr -dc 'A-Za-z0-9')"
fi
[ "$MODE" = "node" ] && [ -n "$HUB_URL" ] && [ -z "$SECRET" ] && {
    echo "a --hub-url needs a --secret (the one the hub printed)." >&2; exit 1; }

echo "==> deps"
apt-get update -qq
if [ "$MODE" = "hub" ]; then
    apt-get install -y --no-install-recommends python3 curl >/dev/null
else
    # fping is the ping probe, iw reads wifi RSSI. That is the entire node dependency list.
    apt-get install -y --no-install-recommends python3 curl fping iw >/dev/null
    bin="$(command -v fping || true)"
    [ -n "$bin" ] && setcap cap_net_raw+ep "$bin" 2>/dev/null && echo "    setcap $bin" || true
fi

echo "==> building agent from $REPO@$BRANCH"
# Source tarball rather than a clone: no git dependency, and nothing left behind to diverge.
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
curl -fsSL "https://codeload.github.com/$REPO/tar.gz/refs/heads/$BRANCH" | tar xz -C "$TMP"
SRC="$(find "$TMP" -maxdepth 1 -type d -name 'smokemon-*' | head -1)"
[ -d "$SRC/smokemon" ] || { echo "unexpected tarball layout" >&2; exit 1; }
find "$SRC/smokemon" -name __pycache__ -type d -exec rm -rf {} + 2>/dev/null || true
install -d /usr/local/lib
python3 -m zipapp "$SRC" -m "smokemon.__main__:main" -p "/usr/bin/env python3" -o "$AGENT.new" -c \
    --compress 2>/dev/null || python3 -m zipapp "$SRC" -m "smokemon.__main__:main" \
    -p "/usr/bin/env python3" -o "$AGENT.new" -c
# Swap in atomically: a half-written agent that systemd then restarts into is worse than a
# brief window of the old one still running.
mv "$AGENT.new" "$AGENT"; chmod 755 "$AGENT"
echo "    $AGENT ($(du -h "$AGENT" | cut -f1))"

echo "==> service user + data dir"
id -u "$SVC_USER" >/dev/null 2>&1 || useradd --system --no-create-home --shell /usr/sbin/nologin "$SVC_USER"
# 755, not 750: the daemon writes as $SVC_USER but `smoke` is run by whoever is logged in, and
# a mode that stops an admin reading their own node's incidents just teaches them to use sudo
# for everything. Nothing secret lives here -- incidents and heartbeats. The shared secret is
# in $ENV_FILE at 640 root:$SVC_USER, which is where the restriction belongs.
install -d -o "$SVC_USER" -g "$SVC_USER" -m 755 "$DATA_DIR"

echo "==> $ENV_FILE"
{
    echo "# smokemon config (generated by install.sh)"
    echo "SMOKEMON_NODE=$NODE_NAME"
    if [ "$MODE" = "hub" ]; then
        echo "SMOKEMON_HUB_DB=$DATA_DIR/hub.db"
        echo "SMOKEMON_HUB_BIND=0.0.0.0"
        echo "SMOKEMON_HUB_PORT=8765"
    else
        echo "SMOKEMON_DB=$DATA_DIR/node.db"
        echo "SMOKEMON_TARGETS=$TARGETS"
        [ -n "$HUB_URL" ] && echo "SMOKEMON_HUB_URL=$HUB_URL"
    fi
    echo "SMOKEMON_HUB_SECRET=$SECRET"
} > "$ENV_FILE"
chmod 640 "$ENV_FILE"; chown root:"$SVC_USER" "$ENV_FILE"

echo "==> smoke command"
cat > /usr/local/bin/smoke <<EOF
#!/bin/sh
# smokemon viewer (generated by install.sh)
export SMOKEMON_DB="$DATA_DIR/node.db"
export SMOKEMON_HUB_DB="$DATA_DIR/hub.db"
export SMOKEMON_NODE="$NODE_NAME"
exec "$AGENT" "\$@"
EOF
chmod 755 /usr/local/bin/smoke

unit() {
    sed -e "s|__USER__|$SVC_USER|g" -e "s|__PYTHON__|$(command -v python3)|g" \
        -e "s|__ENV_FILE__|$ENV_FILE|g" -e "s|__AGENT__|$AGENT|g" \
        -e "s|__DATA_DIR__|$DATA_DIR|g" "$SRC/deploy/systemd/$1" > "$UNIT_DIR/$1"
}

echo "==> systemd"
# Retire the units this replaces. Leaving them enabled would run a second collector against
# the same database -- the write contention the single-process design exists to remove.
for old in smokemon-collect-fast.service smokemon-collect-slow.service \
           smokemon-shipper.service smokemon-shipper.timer \
           smokemon-prune.service smokemon-prune.timer \
           smokemon-iperf.service smokemon-iperf.timer smokemon-iperf-server.service; do
    systemctl disable --now "$old" >/dev/null 2>&1 || true
    rm -f "$UNIT_DIR/$old"
done
# A unit removed while it was in a failed state leaves a "not-found failed" entry behind that
# shows up in every `systemctl list-units` and in any health check that greps for failures.
systemctl reset-failed 'smokemon*' >/dev/null 2>&1 || true

if [ "$MODE" = "hub" ]; then
    unit smokemon-hub.service
    install -m 755 "$SRC/scripts/fleet-reprovision.sh" /usr/local/bin/smokemon-fleet
    systemctl daemon-reload
    systemctl enable smokemon-hub.service
    # restart, not `enable --now`: on a box that already runs smokemon, --now sees an active
    # unit and does nothing, so a reinstall silently leaves the OLD agent running against the
    # new files. Every install must end with the code that was just written actually executing.
    systemctl restart smokemon-hub.service
    IP="$(tailscale ip -4 2>/dev/null | head -1 || hostname -I | awk '{print $1}')"
    cat <<EOF

==> hub running on http://$IP:8765/

    roll out to the fleet (reads the secret from $ENV_FILE):
      sudo smokemon-fleet --tailscale 'aspace-prod-*' --ssh-user aspace

    or install one node by hand:
      curl -fsSL https://raw.githubusercontent.com/$REPO/$BRANCH/install.sh | sudo bash -s -- \\
        --hub-url http://$IP:8765/ingest --secret $SECRET
EOF
else
    unit smokemon.service
    systemctl daemon-reload
    systemctl enable smokemon.service
    systemctl restart smokemon.service   # see the hub branch: --now would not replace a running agent
    echo
    echo "==> node running.  journalctl -u smokemon -f   |   smoke incidents"
    [ -z "$HUB_URL" ] && echo "    (no --hub-url given: running standalone, shipping nothing)"
fi
