#!/usr/bin/env bash
# smokemon Linux installer (Raspberry Pi / Jetson / Debian-like). Installs deps, grants
# fping/mtr CAP_NET_RAW (no sudo), writes /etc/smokemon.env, installs systemd units.
# Run as root.
#
#   NODE: sudo deploy/install_linux.sh --node pi-livingroom \
#             --hub-url http://HUB-HOST:8765/ingest --secret YOUR_SECRET
#   HUB:  sudo deploy/install_linux.sh --hub --secret YOUR_SECRET
#
# Node runs collect fast/slow + ships every 60s + iperf every 15 min.
# Hub runs the ingest server. --secret must match between node and hub.
set -euo pipefail

MODE="node"; NODE_NAME="$(hostname)"; HUB_URL="http://HUB-HOST:8765/ingest"
SECRET=""; TARGETS="1.1.1.1,192.168.0.1"
while [ $# -gt 0 ]; do
    case "$1" in
        --hub) MODE="hub"; shift ;;
        --node) NODE_NAME="$2"; shift 2 ;;
        --hub-url) HUB_URL="$2"; shift 2 ;;
        --secret) SECRET="$2"; shift 2 ;;
        --targets) TARGETS="$2"; shift 2 ;;
        *) echo "unknown argument: $1" >&2; exit 1 ;;
    esac
done
[ "$(id -u)" -eq 0 ] || { echo "run as root (sudo)." >&2; exit 1; }

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
USER_NAME="${SUDO_USER:-$(whoami)}"
PYTHON="$(command -v python3)"
ENV_FILE="/etc/smokemon.env"
UNIT_DIR="/etc/systemd/system"
echo "==> smokemon install: mode=$MODE dir=$DIR user=$USER_NAME python=$PYTHON"

echo "==> apt deps"
apt-get update -qq
if [ "$MODE" = "hub" ]; then
    apt-get install -y --no-install-recommends iperf3 python3-matplotlib python3-numpy
else
    apt-get install -y --no-install-recommends fping iperf3 iw mtr-tiny
    echo "==> CAP_NET_RAW on fping/mtr (skip sudo)"
    for bin in "$(command -v fping || true)" "$(command -v mtr-packet || true)"; do
        [ -n "$bin" ] && setcap cap_net_raw+ep "$bin" && echo "    setcap $bin" || true
    done
    sudo -u "$USER_NAME" "$PYTHON" -m pip install --user plotext 2>/dev/null \
        || sudo -u "$USER_NAME" "$PYTHON" -m pip install --user --break-system-packages plotext 2>/dev/null \
        || echo "    (plotext skipped — install manually for local TUI)"
fi

echo "==> writing $ENV_FILE"
{
    echo "# smokemon config (generated by install_linux.sh)"
    echo "PYTHONPATH=$DIR"
    echo "SMOKEMON_DB=$DIR/data/smokemon.db"
    echo "SMOKEMON_NODE=$NODE_NAME"
    if [ "$MODE" = "hub" ]; then
        echo "SMOKEMON_HUB_DB=$DIR/data/smokemon-hub.db"
        echo "SMOKEMON_HUB_BIND=0.0.0.0"
        echo "SMOKEMON_HUB_PORT=8765"
    else
        echo "SMOKEMON_TARGETS=$TARGETS"
        echo "SMOKEMON_MTR_SUDO=0"
        echo "SMOKEMON_HUB_URL=$HUB_URL"
    fi
    echo "SMOKEMON_HUB_SECRET=$SECRET"
} > "$ENV_FILE"
chmod 600 "$ENV_FILE"
mkdir -p "$DIR/data"; chown -R "$USER_NAME" "$DIR/data"

install_unit() {
    sed -e "s|__USER__|$USER_NAME|g" -e "s|__SMOKEMON_DIR__|$DIR|g" \
        -e "s|__PYTHON__|$PYTHON|g" -e "s|__ENV_FILE__|$ENV_FILE|g" \
        "$DIR/deploy/systemd/$1" > "$UNIT_DIR/$1"
    echo "    installed $1"
}

echo "==> systemd units"
if [ "$MODE" = "hub" ]; then
    install_unit smokemon-hub.service
    systemctl daemon-reload
    systemctl enable --now smokemon-hub.service
    echo "==> done. Hub listening on :8765 — systemctl status smokemon-hub"
else
    for u in smokemon-collect-fast.service smokemon-collect-slow.service \
             smokemon-iperf.service smokemon-iperf.timer \
             smokemon-shipper.service smokemon-shipper.timer; do install_unit "$u"; done
    systemctl daemon-reload
    systemctl enable --now smokemon-collect-fast.service smokemon-collect-slow.service \
        smokemon-iperf.timer smokemon-shipper.timer
    echo "==> done. journalctl -u smokemon-collect-fast -f"
fi
